### PR TITLE
Fixed dockerizer and run to work again on AWS Batch

### PR DESCRIPTION
**Pull request by tmwong2003**
This PR fixes Disdat so that we can run user-defined transforms in Docker images using AWS Batch.

1. Shrinks the size of `dockerizer` images by no longer using Miniconda as the default Python distribution.
1. Treats an absence of either input or output bundle tags as an empty optional parameter in the Docker image entry point, instead of trying to do fancy things with encoding/decoding "empty" JSON dictionaries.

Unfortunately, somewhere along the line JSON encoding/decoding of tags is (still) broken. Also, for reasons I don't understand `pip` cannot find a TensorFlow package - either source _or_ wheel - to install on Ubuntu 16.04-based images, so I removed TensorFlow from the examples `setup.py` for the time being.

*Update*: `pip` now finds the TensorFlow prebuilt package; the issue was that we were suppressing installation of `manylinux` wheels, which we had to do for historical reasons that no longer apply.

### CODE REVIEW

**Comment by kyocum** [comment]
We will need to keep tensorflow in the setup.py and figure out another way to get TF into 16.04.    I created a 2.7 venv using venv wrappers and successfully 'pip install tensorflow'.

**Comment by kyocum** [comment]
Need to find a better way to get ones aws keys on the container for aws service permissions.

**Comment by tmwong2003** [comment]
I’ll put `tensorflow` back.

**Comment by tmwong2003** [comment]
Passing around AWS credentials is tricky, because of the issues associated with leaving `AWS_SECRET_ACCESS_KEY` in the clear in the job definition environment variable. I suspect that the way forward is to have an IAM role available that can both owns the EC2 instances in the compute cluster and has S3 read/write access.

**Comment by tmwong2003** [comment]
After some experiments with IAM, roles, and the AWS CLI (ugh), I have one other solution. Assuming that the IAM role that spawned the batch cluster EC2 instances (such as `ecsInstanceRole`) does _not_ have S3 read/write access, we can use the AWS STS to obtain a temporary session token for the batch run, and pass the temporary credentials and session tokens as environment variables to be set by the job. The downside is that the tokens are visible and usable to anyone with AWS Batch web console access until the session expires.

screen shot 2018-01-26 at 11 40 19 pm

**Pull request merged**
